name: Build
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.2.0"
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - name: install-linter
      run: |
        luarocks install luacheck
    - name: run-linter
      run: |
        make lint

  build-and-test:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@master
      - name: Docker Build
        run: make build
      - name: Run Tests
        run: make test
      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: make push TAG=${{ steps.get_version.outputs.VERSION }}
