name: Build
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Docker Build
        run: make build
      - name: Run Tests
        run: make test
